// Code generated by https://github.com/abakum/embed-encrypt; DO NOT EDIT.

package main

import (
	"embed"
	"github.com/abakum/embed-encrypt/encryptedfs"
	"public/tool"
)

var key []byte

func init() {
	key = tool.Priv("key", "tool")
}

//go:embed "hello.txt.enc"
var helloEnc string

func init() {
	hello = encryptedfs.DecString(helloEnc, key)
}

//go:embed "image/gopher.png.enc"
var gopherEnc []byte

func init() {
	gopher = encryptedfs.DecByte(gopherEnc, key)
}

//go:embed "hello.txt.enc" "another.txt.enc" "with spaces .txt.enc" "image/gopher.png.enc"
var multiplefilesEnc embed.FS

func init() {
	multiplefiles = encryptedfs.InitFS(multiplefilesEnc, key)
}

//go:embed "image/gopher.png.enc" "another.txt.enc" "hello.txt.enc" "with spaces .txt.enc"
var globEnc embed.FS

func init() {
	glob = encryptedfs.InitFS(globEnc, key)
}
